config/routes.rb
Rails.application.routes.draw do
  root to: "dashboards#show"
  resource :dashboard, only: :show
  resources :stories, only: [:index, :show]
  resources :api_responses, only: [:index, :show]
  resources :photos, only: [:index, :show]
  get "/download", to: "downloads#start"
  get "/search", to: "searches#show"
end

app/models/api_response.rb
# coding: utf-8
class ApiResponse < ActiveRecord::Base
  default_scope { order(created_at: "DESC") }
  has_many :stories

  def status
    "#{code} #{message}"
  end

  def server_response_time
  end

  def cms_ids
    extract("cms_ids", [0])
  end

  def stories_retrieved
    cms_ids.length
  end

  def cms_id_range
    head = cms_ids.first
    last = cms_ids.last
    head == last ? head : "#{head}–#{last}"
  end

  def extract(key, default = "")
    hash = JSON.parse(body)
    hash.key?(key) ? hash[key] : default
  rescue
    default
  end

  def initiated_at_formatted
    date = initiated_at.in_time_zone("Central Time (US & Canada)")
    date.strftime("%Y-%m-%d %H:%M:%S")
  end

  def elapsed_seconds
    "#{(elapsed_time / 1000).round(2)} s"
  end
end

app/models/archive.rb
require "zip"

class Archive < ActiveRecord::Base
  def self.buffer
    buffer = Zip::OutputStream.write_buffer do |zos|
      Story.all.each do |story|
        zos.put_next_entry "article-#{story.cms_id}.xml"
        zos.puts Nitf::Story.new(story).xml
      end
    end

    buffer.string.force_encoding("binary")
  end
end

class NoArchive
  def payload=(binary)
    Archive.create(payload: binary)
  end
end

app/models/category_section_mapping.rb
class CategorySectionMapping < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :photo_id, uniqueness: true
  has_and_belongs_to_many :stories
end

app/models/story.rb
class Story < ActiveRecord::Base
  default_scope { order(created_at: "DESC") }
  validates :cms_id, presence: true, uniqueness: true
  has_and_belongs_to_many :photos
  belongs_to :api_response

  DEFAULT_SECTION = "baton_rouge/news".freeze

  module States
    NEW = 1
    PROCESSING = 2
    DONE = 3
    ERROR = 4
  end

  def section
    mapping = CategorySectionMapping.where(
      category: category,
      subcategory: subcategory
    ).first || NoCategorySectionMapping.new

    mapping.section
  end

  def nitf
    nitf = Nitf::Story.new(self)
    puts nitf.builder.to_xml
  end

  def nitf_publish_date
    date = publish_date || NoPublishDate.new
    zoned = date.in_time_zone("Central Time (US & Canada)")
    zoned.strftime("%Y%m%dT%H%M%S")
  end
  
  def published_at
    date = publish_date || NoPublishDate.new
    zoned = date.in_time_zone("Central Time (US & Canada)")
    zoned.strftime("%Y-%m-%d %l:%M %p")
  end

  class NoPublishDate
    def in_time_zone(zone)
      self
    end

    def strftime(str)
      "-"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/api_responses_controller.rb
class ApiResponsesController < ApplicationController
  before_action :require_login

  def index
    @api_responses = ApiResponse.paginate(page: params[:page], per_page: 25)
  end

  def show
    @api_response = ApiResponse.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @api_responses = ApiResponse.all
    @stories = Story.take(5)
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  before_action :render_nothing

  def start
  end

  private

  def render_nothing
    render nothing: true
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :require_login
  before_action :set_photo, only: :show

  def index
    @photos = Photo.all
  end

  def show
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :require_login

  def show
    @stories = Story.where(cms_id: params[:cms_id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :require_login

  def index
    @stories = Story.paginate(page: params[:page], per_page: 25)
  end

  def show
    @story = Story.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def side_nav_class(nav_item, has_children = true)
    klass = "" + nav_item
    klass << " has-children" if has_children
    klass << " active" if active_page?(nav_item)
    klass
  end

  def active_page?(klass)
    controller = body_class.split[0]
    page = controller == "dashboards" ? "dashboard" : controller
    page == klass
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def stories_chart_data
    labels = []
    series = []
    stories_processed = 0
    @api_responses.each do |api_response|
      # labels << api_response.created_at
      labels << ""
      stories_processed += api_response.stories_retrieved
      series << stories_processed
    end

    { labels: labels, series: [series] }.to_json
  end

  def stories_chart_options
    {
      axisY: { onlyInteger: true },
      showArea: true
    }.to_json
  end

  def stories_chart
    html = <<HTML
      <div id='stories-chart' class='ct-chart ct-golden-section'></div>
      <script>
        new Chartist.Line('#stories-chart', #{stories_chart_data}, #{stories_chart_options});
      </script>
HTML
    html.html_safe
  end

  def stories_pie
    stories_count = Story.count
    data = {
      labels: %w(Imported Remaining),
      series: [stories_count, 147_000 - stories_count]
    }.to_json
    html = <<HTML
      <div id='stories-pie' class='ct-chart ct-golden-section'></div>
      <script>
        new Chartist.Pie('#stories-pie', #{data});
      </script>
HTML
    html.html_safe
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/api_responses/index.html.haml
%h1.page-title API Responses

%table.api-responses
  %thead
    %tr
      %th Status
      %th Start ID
      %th Num Stories
      %th Initiated
      %th Elapsed
      %th CMS ID(s)
      %th
  %tbody
    - @api_responses.each do |api_response|
      %tr.api-response
        %td.api-response__status
          %span{class: "http-status http-status--#{api_response.status.gsub(/ /, '_')}"}= api_response.status
        %td= api_response.start_id
        %td= api_response.num_stories
        %td.api-response__initiated-at= api_response.initiated_at_formatted
        %td.api-response__elapsed-time= api_response.elapsed_seconds
        %td.api-response__cms-ids= api_response.cms_id_range
        %td= link_to "View", api_response_path(api_response.id, format: :json)

%hr/
    
.pagination-wrapper
  = will_paginate @stories

app/views/api_responses/show.json.haml
= @api_response.body.html_safe

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_analytics.html.haml
- if ENV["SEGMENT_KEY"]
  :javascript
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("#{ENV["SEGMENT_KEY"]}");
    window.analytics.page();

app/views/application/_flashes.html.haml
- if flash.any?
  .flashes
    - user_facing_flashes.each do |key, value|
      %div{:class => "flash-#{key}"}= value

app/views/application/_javascript.html.haml
= javascript_include_tag :application
= yield :javascript
= render "analytics"
- if Rails.env.test?
  = javascript_tag do
    $.fx.off = true;
    $.ajaxSetup({ async: false });

app/views/application/_session.html.haml
- if signed_in?
  %li.has-children.account
    = link_to current_user.email, "#0"
    %ul
      %li= link_to "Sign out", sign_out_path, method: :delete
- else
  %li
    %strong= link_to "Sign in", sign_in_path

app/views/application/_side_nav.html.haml
%nav.cd-side-nav
  %ul
    %li.cd-label Content
    %li{class: side_nav_class("dashboard", false)}
      = link_to "Dashboard", dashboard_path
    %li{class: side_nav_class("stories")}
      = link_to "Stories", stories_path
    %li{class: side_nav_class("api_responses")}
      = link_to "API Log", api_responses_path
  %ul
    %li.cd-label Actions
    %li.action-btn= link_to "⬇ Download Archive", "/download"

app/views/dashboards/show.html.haml
.charts
  #stories-imported.panel
    %h1.panel__title Stories Imported
    .panel__content
      .big-number= number_with_delimiter(Story.count)

  #stories-total.panel
    %h1.panel__title Stories Remaining
    .panel__content
      = stories_pie

#recent-imports
  %h1 Recent imports
  %ul
    - @stories.each do |story|
      = render partial: "stories/story", locals: { story: story }

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "NOODP", :name => "ROBOTS"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= title
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Merriweather:400,400italic,700,700italic|Source+Code+Pro"
    = stylesheet_link_tag :application, media: "all"
    = javascript_include_tag :chartist
    = javascript_include_tag :modernizr
    = csrf_meta_tags
  %body{class: body_class}
    %header.cd-main-header
      .cd-search.is-hidden
        %form{action: "/search", method: "get"}
          %input{placeholder: "Search by CMS ID", type: "search", name: "cms_id"}/
      %a.cd-nav-trigger{href: "#0"}
        Menu
        %span
      %nav.cd-nav
        %ul.cd-top-nav
          %li
            %a{href: "https://github.com/ngscheurich/ccp-archiver"} Code
          %li
            %a{href: "mailto:nscheurich@theadvocate.com?subject=CCP%20Archiver"} Support
          = render "session"
    %main.cd-main-content
      = render "side_nav"
      .content-wrapper
        .content
          = render "flashes"
          = yield
    = render "javascript"

app/views/photos/index.html.haml
%ul
  - @photos.each do |photo|
    %li.photo= link_to image_tag(photo.source), photo
  

app/views/photos/show.html.haml
=image_tag(@photo.source)

%dl
  %dt Photo ID
  %dd= @photo.photo_id
  %dt Byline
  %dd= @photo.byline
  %dt Credit
  %dd= @photo.credit
  %dt Caption
  %dd= @photo.caption

app/views/searches/show.html.haml
%h1.page-title Results

%ul
  - @stories.each do |story|
    = render partial: "stories/story", locals: { story: story }

app/views/stories/_story.html.haml
%li.story.card.card--story
  %header.card__header
    %h1.card__title.story__headline= link_to story.headline.html_safe, story
    .cover
  %ul.card__info
    %li.card__info-segment
      %h2.card__info-segment-key CMS ID
      .card__info-segment-val.story__cms-id= story.cms_id
    %li.card__info-segment
      %h2.card__info-segment-key Published At
      .card__info-segment-val.story__created-at= story.published_at
    %li.card__info-segment
      %h2.card__info-segment-key Category 
      .card__info-segment-val= story.category
    %li.card__info-segment
      %h2.card__info-segment-key Subcategory 
      .card__info-segment-val= story.subcategory

app/views/stories/index.html.haml
%h1.page-title Stories

%ul
  - @stories.each do |story|
    = render partial: "story", locals: { story: story }

%hr/
    
.pagination-wrapper
  = will_paginate @stories

app/views/stories/show.html.haml
.h-entry
  %article
    %h1.p-name= @story.headline.html_safe
    .p-author= @story.byline.html_safe
    %hr
    .e-content
      = @story.body.html_safe
  %aside
    = link_to "View NITF", story_path(@story.id, format: :xml), class: "action-btn"
    %dl.story
      %dt CMS ID
      %dd.story__cms-id= @story.cms_id
      %dt Publish Date
      %dd= @story.published_at
      %dt Category/Subcategory
      %dd= "#{@story.category}/#{@story.subcategory}" || "–"
      %dt Keywords
      %dd= @story.keywords || "–"

%hr

.photos
  %ul
    - @story.photos.each do |photo|
      %li.photo= link_to image_tag(photo.source), photo
      

app/views/stories/show.xml.erb
<%= raw(Nitf::Story.new(@story).xml) %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>